title: Measuring college opportunity
siteurl: /collegeopp
github: https://github.com/btskinner/collegeopp
mail: btskinner@virginia.edu

date_format: "%d %B %Y"

google_analytics: UA-63981025-1
disqus_shortname:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']
permalink:    pretty
